### ISSUE TITLE
Rake aborted

### ISSUE THREAD

**Issue by simone24** [myExperiment/myExperiment#14]
Hello,
I'm Simone and I would like to ask about a problem with the command **bundle exec rake db:migrate --trace**.
I've installed myExperiment in Ubuntu 12.04 LTS following the instructions in http://wiki.myexperiment.org/index.php/Developer:UbuntuInstallation and everything worked fine till the command **bundle exec rake db:create:all**
But when I launch the command **bundle exec rake db:migrate --trace** it returns the  following error:
_** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
Rails Error: Unable to access log file. Please ensure that /opt/myExperiment/log/development.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
rake aborted!
undefined method `[]' for false:FalseClass
/opt/myExperiment/lib/conf.rb:339:in `fetch_entry'
/opt/myExperiment/lib/conf.rb:181:in `cookie_verifier_secret'
/opt/myExperiment/config/initializers/cookie_verification_secret.rb:7:in `<top (required)>'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:171:in `load'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:171:in `block in load_with_new_constant_marking'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:547:in `new_constants_in'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:171:in `load_with_new_constant_marking'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rails-2.3.18/lib/initializer.rb:622:in `block in load_application_initializers'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rails-2.3.18/lib/initializer.rb:621:in `each'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rails-2.3.18/lib/initializer.rb:621:in `load_application_initializers'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rails-2.3.18/lib/initializer.rb:176:in `process'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rails-2.3.18/lib/initializer.rb:113:in `run'
/opt/myExperiment/config/environment.rb:12:in `<top (required)>'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:182:in `require'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:182:in `block in require'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:547:in `new_constants_in'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:182:in `require'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rails-2.3.18/lib/tasks/misc.rake:4:in `block in <top (required)>'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/home/myexp/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/home/myexp/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/bin/rake:19:in `load'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/bin/rake:19:in `<main>'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/bin/ruby_executable_hooks:15:in `eval'
/home/myexp/.rvm/gems/ruby-1.9.2-p320@myexperiment/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment_

Thanks in advance for your help
Simone

**Comment by fbacall** [comment]
Hi Simone,

This was due to a bug that occurs when your "settings.yml" file is empty. I've just fixed it, so if you do a `git pull origin master` (assuming you are using the `master` branch) then re-run the `bundle exec rake db:migrate` command, it should work.

Cheers

**Comment by simone24** [comment]
Thanks, it works!!!!

Simone
