### ISSUE TITLE
[SOLVED] SMTP

### ISSUE THREAD

**Issue by simone24** [myExperiment/myExperiment#16]
Hello,
I'm here again.
I'm tryng to set smtp to send email for user registration, but mail isn't send.

At the moment I set this part of **settings.yml**:

notifications_email_address: myemail   # here I wrote my email address

feedback_email_address: myemail     # here I wrote my email address again

........... and .......

smtp:

       :address:        "smtp.example.org" # I wrote the address of my smtp. I've also tried whith IP address
       :port:           25,
       :domain:         "" # I left it empty
       :authentication: login  # I didn't understand which other values has this options
       :user_name:      "username" # I wrote my user
       :password:       "password" # I wrote the password

Are there other files to modify?
Could someone tell me the values of **authentication** option?

Thanks
Simone

**Comment by fbacall** [comment]
Hi Simone,

Those configurations are part of Rails' ActionMailer config, which you can find info about here:
https://apidock.com/rails/v2.3.8/ActionMailer/Base

Re: authentication, the settings are:
> If your mail server requires authentication, you need to specify the authentication type here. This is a symbol and one of `:plain`, `:login`, `:cram_md5`.

Make sure you include the ":" as it is expecting a ruby symbol.

I don't have too much experience configuring the email myself, but on myexperiment.org we use GMail to send emails, and the settings are:
```
smtp:
  :address:        "smtp.gmail.com"
  :port:           587,
  :domain:         "mail.myexperiment.org"
  :authentication: :login
  :user_name:      "<username>@mail.myexperiment.org"
  :password:       "<password>"
```

**Comment by simone24** [comment]
Thanks, I will try.
Since I don't know where this operation fails, I don't find any log file except _development.log_ in **myExperiment/log** where I can't find anything about the email error.
Is there the possibility to trace this kind of error?

Simone

**Comment by simone24** [comment]
Hi,
I've tried with my googlemail account, and it works.
I've already treied with anothr googlemail account... and it doensn't work. In this account the password is composed by some special character like ":". Could this be interpreted in a wrong way by myExperiment?

Simone

**Comment by fbacall** [comment]
I think sending of email is handled by the OS, so if you are using Ubuntu, maybe look in `/var/log/maillog` for any error messages. Sometimes GMail requires some extra authentication before it allows you to send emails through it.

Special characters should be fine in passwords, as long as it is surrounded by `"` quotes.

**Comment by simone24** [comment]
Solved.
To allow gmail smtp to send email from other application you have to set the option _Allow less secure apps: ON_ in _Sign in & Security --> Apps whit account access_ from Google Account

Thanks, now everything is working

Simone
