### ISSUE TITLE
Issue with password restore on Android

### ISSUE THREAD

**Issue by mdziczkowski** [myExperiment/myExperiment#37]
## OS:

Tested on Android 13, on browsers: Firefox, Opera and Brave

## Issue:

While attempting to restore the password on myexperiment.org, in some cases it was displaying the error 500 (server missconfiguration).

Attaching screenshoot

![Screenshot_2023-12-03-14-45-08-21_3aea4af51f236e4932235fdada7d1643](https://github.com/myExperiment/myExperiment/assets/154359/317051ca-3c45-4589-a9fe-7b9f640f8f7f)

**Comment by fbacall** [comment]
Thanks for the report, we are investigating this

**Comment by fbacall** [comment]
This should now be resolved
